### ISSUE TITLE
Tensor To Json conversion doesn't work on negative shape numbers (-1)

### ISSUE THREAD

**Issue by tidylobster** [Hydrospheredata/hydro-serving-protos#28]
```ERROR[hydroserving-gateway-akka.actor.default-dispatcher-12] 2019-02-27 10:29:29,372 HttpApi.applyOrElse.30  null
java.lang.NegativeArraySizeException: null
        at io.hydrosphere.serving.model.api.json.DimShaper.shapeGrouped$1(DimShaper.scala:41) ~[serving-grpc-scala_2.12-0.1.22.jar:0.1.22]
        at io.hydrosphere.serving.model.api.json.DimShaper.shape(DimShaper.scala:52) ~[serving-grpc-scala_2.12-0.1.22.jar:0.1.22]
        at io.hydrosphere.serving.model.api.json.TensorJsonLens.toJson(TensorJsonLens.scala:15) ~[serving-grpc-scala_2.12-0.1.22.jar:0.1.22]
        at io.hydrosphere.serving.model.api.json.TensorJsonLens.toJson$(TensorJsonLens.scala:12) ~[serving-grpc-scala_2.12-0.1.22.jar:0.1.22]
        at io.hydrosphere.serving.model.api.json.Int64ToJson$.toJson(Int64ToJson.scala:6) ~[serving-grpc-scala_2.12-0.1.22.jar:0.1.22]
        at io.hydrosphere.serving.model.api.json.TensorJsonLens$.toJson(TensorJsonLens.scala:24) ~[serving-grpc-scala_2.12-0.1.22.jar:0.1.22]
        at io.hydrosphere.serving.gateway.service.ApplicationExecutionServiceImpl.$anonfun$responseToJsObject$1(ApplicationExecutionService.scala:303) ~[app.jar:0.0.2-SNAPSHOT]
        at scala.collection.MapLike$MappedValues.$anonfun$foreach$3(MapLike.scala:253) ~[scala-library.jar:?]
        at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:789) ~[scala-library.jar:?]
        at scala.collection.immutable.Map$Map4.foreach(Map.scala:233) ~[scala-library.jar:?]
        at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:788) ~[scala-library.jar:?]
        at scala.collection.MapLike$MappedValues.foreach(MapLike.scala:253) ~[scala-library.jar:?]
        at spray.json.JsonPrinter.printSeq(JsonPrinter.scala:90) ~[spray-json_2.12-1.3.4.jar:?]
        at spray.json.JsonPrinter.printSeq$(JsonPrinter.scala:88) ~[spray-json_2.12-1.3.4.jar:?]
        at spray.json.CompactPrinter$.printSeq(CompactPrinter.scala:51) ~[spray-json_2.12-1.3.4.jar:?]
        at spray.json.CompactPrinter.printObject(CompactPrinter.scala:36) ~[spray-json_2.12-1.3.4.jar:?]
        at spray.json.CompactPrinter.printObject$(CompactPrinter.scala:34) ~[spray-json_2.12-1.3.4.jar:?]
        at spray.json.CompactPrinter$.printObject(CompactPrinter.scala:51) ~[spray-json_2.12-1.3.4.jar:?]
        at spray.json.CompactPrinter.print(CompactPrinter.scala:28) ~[spray-json_2.12-1.3.4.jar:?]
        at spray.json.CompactPrinter.print$(CompactPrinter.scala:26) ~[spray-json_2.12-1.3.4.jar:?]
        at spray.json.CompactPrinter$.print(CompactPrinter.scala:51) ~[spray-json_2.12-1.3.4.jar:?]
        at spray.json.JsonPrinter.apply(JsonPrinter.scala:37) ~[spray-json_2.12-1.3.4.jar:?]
        at spray.json.JsonPrinter.apply$(JsonPrinter.scala:29) ~[spray-json_2.12-1.3.4.jar:?]
        at spray.json.CompactPrinter$.apply(CompactPrinter.scala:51) ~[spray-json_2.12-1.3.4.jar:?]
        at spray.json.JsonPrinter.apply(JsonPrinter.scala:27) ~[spray-json_2.12-1.3.4.jar:?]
        at spray.json.JsonPrinter.apply$(JsonPrinter.scala:27) ~[spray-json_2.12-1.3.4.jar:?]
        at spray.json.CompactPrinter$.apply(CompactPrinter.scala:51) ~[spray-json_2.12-1.3.4.jar:?]
        at spray.json.CompactPrinter$.apply(CompactPrinter.scala:51) ~[spray-json_2.12-1.3.4.jar:?]
        at akka.http.scaladsl.marshalling.Marshaller.$anonfun$wrapWithEC$2(Marshaller.scala:43) ~[akka-http_2.12-10.0.11.jar:?]
        at akka.http.scaladsl.marshalling.Marshaller$$anon$1.apply(Marshaller.scala:92) ~[akka-http_2.12-10.0.11.jar:?]
        at akka.http.scaladsl.marshalling.PredefinedToResponseMarshallers.$anonfun$fromStatusCodeAndHeadersAndValue$2(PredefinedToResponseMarshallers.scala:62) ~[akka-http_2.12-10.0.11.jar:?]
        at akka.http.scaladsl.marshalling.Marshaller$$anon$1.apply(Marshaller.scala:92) ~[akka-http_2.12-10.0.11.jar:?]
        at akka.http.scaladsl.marshalling.Marshaller.$anonfun$compose$2(Marshaller.scala:73) ~[akka-http_2.12-10.0.11.jar:?]
        at akka.http.scaladsl.marshalling.Marshaller$$anon$1.apply(Marshaller.scala:92) ~[akka-http_2.12-10.0.11.jar:?]
        at akka.http.scaladsl.marshalling.GenericMarshallers.$anonfun$eitherMarshaller$2(GenericMarshallers.scala:28) ~[akka-http_2.12-10.0.11.jar:?]
        at akka.http.scaladsl.marshalling.Marshaller$$anon$1.apply(Marshaller.scala:92) ~[akka-http_2.12-10.0.11.jar:?]
        at akka.http.scaladsl.marshalling.GenericMarshallers.$anonfun$futureMarshaller$3(GenericMarshallers.scala:33) ~[akka-http_2.12-10.0.11.jar:?]
        at akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:41) ~[akka-http-core_2.12-10.0.11.jar:?]
        at akka.http.scaladsl.util.FastFuture$.$anonfun$transformWith$3(FastFuture.scala:51) ~[akka-http-core_2.12-10.0.11.jar:?]
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60) ~[scala-library.jar:?]
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55) ~[akka-actor_2.12-2.5.8.jar:?]
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91) ~[akka-actor_2.12-2.5.8.jar:?]
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12) [scala-library.jar:?]
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81) [scala-library.jar:?]
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91) [akka-actor_2.12-2.5.8.jar:?]
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40) [akka-actor_2.12-2.5.8.jar:?]
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43) [akka-actor_2.12-2.5.8.jar:?]
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [akka-actor_2.12-2.5.8.jar:?]
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [akka-actor_2.12-2.5.8.jar:?]
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [akka-actor_2.12-2.5.8.jar:?]
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [akka-actor_2.12-2.5.8.jar:?]```

**Comment by tidylobster** [comment]
```ERROR[hydroserving-gateway-akka.actor.default-dispatcher-6] 2019-02-27 11:19:25,537 HttpApi.applyOrElse.30  0
java.lang.IndexOutOfBoundsException: 0
        at scala.collection.immutable.Vector.checkRangeConvert(Vector.scala:123) ~[scala-library.jar:?]
        at scala.collection.immutable.Vector.apply(Vector.scala:114) ~[scala-library.jar:?]
        at io.hydrosphere.serving.model.api.json.DimShaper.shapeGrouped$1(DimShaper.scala:36) ~[serving-grpc-scala_2.12-0.1.22.jar:0.1.22]
        at io.hydrosphere.serving.model.api.json.DimShaper.$anonfun$shape$3(DimShaper.scala:44) ~[serving-grpc-scala_2.12-0.1.22.jar:0.1.22]
        at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:156) ~[scala-library.jar:?]
        at io.hydrosphere.serving.model.api.json.DimShaper.shapeGrouped$1(DimShaper.scala:43) ~[serving-grpc-scala_2.12-0.1.22.jar:0.1.22]
        at io.hydrosphere.serving.model.api.json.DimShaper.$anonfun$shape$3(DimShaper.scala:44) ~[serving-grpc-scala_2.12-0.1.22.jar:0.1.22]
        at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:156) ~[scala-library.jar:?]
        at io.hydrosphere.serving.model.api.json.DimShaper.shapeGrouped$1(DimShaper.scala:43) ~[serving-grpc-scala_2.12-0.1.22.jar:0.1.22]
        at io.hydrosphere.serving.model.api.json.DimShaper.shape(DimShaper.scala:52) ~[serving-grpc-scala_2.12-0.1.22.jar:0.1.22]
        at io.hydrosphere.serving.model.api.json.TensorJsonLens.toJson(TensorJsonLens.scala:15) ~[serving-grpc-scala_2.12-0.1.22.jar:0.1.22]
        at io.hydrosphere.serving.model.api.json.TensorJsonLens.toJson$(TensorJsonLens.scala:12) ~[serving-grpc-scala_2.12-0.1.22.jar:0.1.22]
        at io.hydrosphere.serving.model.api.json.Int64ToJson$.toJson(Int64ToJson.scala:6) ~[serving-grpc-scala_2.12-0.1.22.jar:0.1.22]
        at io.hydrosphere.serving.model.api.json.TensorJsonLens$.toJson(TensorJsonLens.scala:24) ~[serving-grpc-scala_2.12-0.1.22.jar:0.1.22]
        at io.hydrosphere.serving.gateway.service.ApplicationExecutionServiceImpl.$anonfun$responseToJsObject$1(ApplicationExecutionService.scala:303) ~[app.jar:0.0.2-SNAPSHOT]
        at scala.collection.MapLike$MappedValues.$anonfun$foreach$3(MapLike.scala:253) ~[scala-library.jar:?]
        at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:789) ~[scala-library.jar:?]
        at scala.collection.immutable.Map$Map4.foreach(Map.scala:233) ~[scala-library.jar:?]
        at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:788) ~[scala-library.jar:?]
        at scala.collection.MapLike$MappedValues.foreach(MapLike.scala:253) ~[scala-library.jar:?]
        at spray.json.JsonPrinter.printSeq(JsonPrinter.scala:90) ~[spray-json_2.12-1.3.4.jar:?]
        at spray.json.JsonPrinter.printSeq$(JsonPrinter.scala:88) ~[spray-json_2.12-1.3.4.jar:?]
        at spray.json.CompactPrinter$.printSeq(CompactPrinter.scala:51) ~[spray-json_2.12-1.3.4.jar:?]
        at spray.json.CompactPrinter.printObject(CompactPrinter.scala:36) ~[spray-json_2.12-1.3.4.jar:?]
        at spray.json.CompactPrinter.printObject$(CompactPrinter.scala:34) ~[spray-json_2.12-1.3.4.jar:?]
        at spray.json.CompactPrinter$.printObject(CompactPrinter.scala:51) ~[spray-json_2.12-1.3.4.jar:?]
        at spray.json.CompactPrinter.print(CompactPrinter.scala:28) ~[spray-json_2.12-1.3.4.jar:?]
        at spray.json.CompactPrinter.print$(CompactPrinter.scala:26) ~[spray-json_2.12-1.3.4.jar:?]
        at spray.json.CompactPrinter$.print(CompactPrinter.scala:51) ~[spray-json_2.12-1.3.4.jar:?]
        at spray.json.JsonPrinter.apply(JsonPrinter.scala:37) ~[spray-json_2.12-1.3.4.jar:?]
        at spray.json.JsonPrinter.apply$(JsonPrinter.scala:29) ~[spray-json_2.12-1.3.4.jar:?]
        at spray.json.CompactPrinter$.apply(CompactPrinter.scala:51) ~[spray-json_2.12-1.3.4.jar:?]
        at spray.json.JsonPrinter.apply(JsonPrinter.scala:27) ~[spray-json_2.12-1.3.4.jar:?]
        at spray.json.JsonPrinter.apply$(JsonPrinter.scala:27) ~[spray-json_2.12-1.3.4.jar:?]
        at spray.json.CompactPrinter$.apply(CompactPrinter.scala:51) ~[spray-json_2.12-1.3.4.jar:?]
        at spray.json.CompactPrinter$.apply(CompactPrinter.scala:51) ~[spray-json_2.12-1.3.4.jar:?]
        at akka.http.scaladsl.marshalling.Marshaller.$anonfun$wrapWithEC$2(Marshaller.scala:43) ~[akka-http_2.12-10.0.11.jar:?]
        at akka.http.scaladsl.marshalling.Marshaller$$anon$1.apply(Marshaller.scala:92) ~[akka-http_2.12-10.0.11.jar:?]
        at akka.http.scaladsl.marshalling.PredefinedToResponseMarshallers.$anonfun$fromStatusCodeAndHeadersAndValue$2(PredefinedToResponseMarshallers.scala:62) ~[akka-http_2.12-10.0.11.jar:?]
        at akka.http.scaladsl.marshalling.Marshaller$$anon$1.apply(Marshaller.scala:92) ~[akka-http_2.12-10.0.11.jar:?]
        at akka.http.scaladsl.marshalling.Marshaller.$anonfun$compose$2(Marshaller.scala:73) ~[akka-http_2.12-10.0.11.jar:?]
        at akka.http.scaladsl.marshalling.Marshaller$$anon$1.apply(Marshaller.scala:92) ~[akka-http_2.12-10.0.11.jar:?]
        at akka.http.scaladsl.marshalling.GenericMarshallers.$anonfun$eitherMarshaller$2(GenericMarshallers.scala:28) ~[akka-http_2.12-10.0.11.jar:?]
        at akka.http.scaladsl.marshalling.Marshaller$$anon$1.apply(Marshaller.scala:92) ~[akka-http_2.12-10.0.11.jar:?]
        at akka.http.scaladsl.marshalling.GenericMarshallers.$anonfun$futureMarshaller$3(GenericMarshallers.scala:33) ~[akka-http_2.12-10.0.11.jar:?]
        at akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:41) ~[akka-http-core_2.12-10.0.11.jar:?]
        at akka.http.scaladsl.util.FastFuture$.$anonfun$transformWith$3(FastFuture.scala:51) ~[akka-http-core_2.12-10.0.11.jar:?]
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60) ~[scala-library.jar:?]
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55) ~[akka-actor_2.12-2.5.8.jar:?]
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91) ~[akka-actor_2.12-2.5.8.jar:?]
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12) [scala-library.jar:?]
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81) [scala-library.jar:?]
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91) [akka-actor_2.12-2.5.8.jar:?]
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40) [akka-actor_2.12-2.5.8.jar:?]
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43) [akka-actor_2.12-2.5.8.jar:?]
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [akka-actor_2.12-2.5.8.jar:?]
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [akka-actor_2.12-2.5.8.jar:?]
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [akka-actor_2.12-2.5.8.jar:?]
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [akka-actor_2.12-2.5.8.jar:?]
```

Code: 
```python
def predict(imgs=None):
    response_tensor_1_shape = [hs.TensorShapeProto.Dim(size=dim) for dim in [1, 1]]
    response_tensor_1 = hs.TensorProto(
        int_val=[1], dtype=hs.DT_INT64,
        tensor_shape=hs.TensorShapeProto(dim=response_tensor_1_shape))

    response_tensor_2_shape = [hs.TensorShapeProto.Dim(size=dim) for dim in [1, 10]]
    response_tensor_2 = hs.TensorProto(
        float_val=np.random.normal(size=(1, 10)).flatten().tolist(), dtype=hs.DT_FLOAT,
        tensor_shape=hs.TensorShapeProto(dim=response_tensor_2_shape))
    
    response_tensor_3_shape = [hs.TensorShapeProto.Dim(size=dim) for dim in [1, 1]]
    response_tensor_3 = hs.TensorProto(
        string_val=["1".encode()], dtype=hs.DT_STRING,
        tensor_shape=hs.TensorShapeProto(dim=response_tensor_3_shape))

    response_tensor_4_shape = [hs.TensorShapeProto.Dim(size=dim) for dim in [1, 10]]
    response_tensor_4 = hs.TensorProto(
        float_val=np.random.normal(size=(1, 10)).flatten().tolist(), dtype=hs.DT_FLOAT,
        tensor_shape=hs.TensorShapeProto(dim=response_tensor_4_shape))
    
    return hs.PredictResponse(outputs={
        "class_ids": response_tensor_1,
        "probabilities": response_tensor_2,
        "classes": response_tensor_3,
        "logits": response_tensor_4
    })
```
